site_name: Factorial Docs

theme:
  name: "material"

plugins:
- mkdocstrings

nav:
  - Factorial Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
